YG-149 Create API to download Sample CSV file for the selected template
Pepcus/yjsg pull request #63
Opened 2022-09-05 05:48 UTC by pepcus-gajendra

# Related issues

Create API to download Sample CSV file for the selected template

2022-09-05 06:39 UTC, pepcus-mukatip approved these changes
approved

2022-09-05 10:20 UTC, pepcus-ankit requested changes

2022-09-08 07:00 UTC, pepcus-ankit requested changes

2022-09-08 07:00 UTC, pepcus-ankit commented on src/main/java/com/pepcus/appstudent/service/TemplateService.java
> +			System.out.println(exception.getMessage());
We should not commit System.out.println. 
@pepcus-gajendra  @pepcus-mukatip  Please review carefully.

2022-09-08 07:00 UTC, pepcus-ankit commented on src/main/resources/application.properties
> +download.csv.file.path=/resource/
Can we rename this property to more appropriate name like.
csv.template.path

2022-09-19 11:13 UTC, pepcus-mukatip commented on src/main/resources/YG-147.SQL
> +DELIMITER $$
why delimiter used with Alter statement?

2022-10-11 07:23 UTC, pepcus-ankit approved these changes

2022-10-11 07:23 UTC, merged